### ISSUE TITLE
Example in README.md fails to build

### ISSUE THREAD

**Issue by danderson** [go-debos/debos#108]
Just discovered debos, and I love it! I copied the example out of the readme to get started:

```yaml
{{- $image := or .image "debian.tgz" -}}

architecture: arm64

actions:
  - action: debootstrap
    suite: "buster"
    components:
      - main
      - non-free
    mirror: https://deb.debian.org/debian
    variant: minbase

  - action: apt
    packages: [ sudo, openssh-server, adduser, systemd-sysv, firmware-linux ]

  - action: run
    chroot: true
    command: echo debian > /etc/hostname

  - action: pack
    file: {{ $image }}
    compression: gz
```

When I run `debos example.yaml`, the scratch VM boots and starts building, but debootstrap fails near the end of base system installation:

```
<most debootstrap spam snipped>
2018/08/17 19:28:33 Debootstrap (stage 2) | I: Configuring the base system...
2018/08/17 19:28:33 Debootstrap (stage 2) | I: Configuring apt-transport-https...
2018/08/17 19:28:33 Debootstrap (stage 2) | I: Configuring libssl1.1:arm64...
2018/08/17 19:28:34 Debootstrap (stage 2) | I: Configuring openssl...
2018/08/17 19:28:34 Debootstrap (stage 2) | I: Configuring ca-certificates...
2018/08/17 19:29:09 Debootstrap (stage 2) | I: Configuring libc-bin...
2018/08/17 19:29:09 Debootstrap (stage 2) | I: Configuring ca-certificates...
2018/08/17 19:29:18 Debootstrap (stage 2) | I: Base system installed successfully.
2018/08/17 19:29:19 Action `debootstrap` failed at stage Run, error: exec: "systemd-nspawn": executable file not found in $PATH
Powering off.
```

I've only dug a tiny bit, but it looks like systemd-nspawn maybe got split out into its own package, `systemd-container`, and debootstrap isn't aware of this yet? Is there anything debos can do to work around this?

**Comment by danderson** [comment]
Ah, I think I was just confused. Looking at the qemu invocation, it looks like debos is just using the host binaries inside a VM, so I need to install systemd-nspawn on my _host_ system to make things work. When I saw debos was using a VM, I assumed it was bringing its own userspace to run the build. Derp :)

So I guess this is maybe a suggestion for documentation, to make it clear that if a build fails with missing executables, that means you must install them on the host system.

**Comment by obbardc** [comment]
installing the Debian package should "just work" and bring with it all required executables,
