### ISSUE TITLE
Print commandline for commands to be executed

### ISSUE THREAD

**Issue by em-** [go-debos/debos#13]
Sometimes knowing exactly what is getting executed is extremely helpful when debugging an error. Printing the commandline before executing a program provides a good hint to reproduce it (just an hint because there's `fakemachine` and what not to make things more complex, but often that's enough). :)

**Comment by sjoerdsimons** [comment]
Yup generally it would be good to have a verbose mode with more debug output.. And potentially a dry-run one as well (spitting out the templated yaml would be quite useful)

**Comment by sjoerdsimons** [comment]
Fixed with the `--print-recipe` option a while back
