### ISSUE TITLE
Q: How to install grub on the output image?

### ISSUE THREAD

**Issue by sangorrin** [go-debos/debos#131]
Hi,

I haven't seen any yaml examples installing grub but it looks like it is possible (?):
https://github.com/go-debos/debos/commit/aa28780a35fcb2f089c7fd72f79dba86097c17f8

Unfortunately, I have tried running grub-install with the action below, and similar several variants (chroot false, postprocess, ..), without any success:
  - action: run
    description: Install grub
    chroot: true
    command: grub-install /dev/sda

Do you have any hints about how to install grub?

Thanks,
Daniel

**Comment by sangorrin** [comment]
OK, I think this can be implemented with the RAW action. I will post an example soon and close this ticket. But if there is a better way, I would like to know.
Thanks
Daniel

**Comment by sangorrin** [comment]
Finally, I managed to install Grub by using the postprocess flag and a custom script (kpartx, mount, ..). I will post the code on my git account in a few days. If there was a better way, please add a comment.
Thanks

**Comment by d4s** [comment]
I'm able to install grub with actions below and additional script:
```yaml
  - action: apt
    description: bootloader
    packages:
      - grub-efi

  - action: run
    description: Install bootloader
    chroot: false
    script: scripts/setup-grub-bootloader.sh
```
setup-grub-bootloader.sh:
```sh
#!/bin/sh

set -eu

if [ -z  "${ROOTDIR}" ] ; then
  echo "ROOTDIR not given"
  exit 1
fi

mount /dev ${ROOTDIR}/dev/ --bind
mount -t proc proc ${ROOTDIR}/proc
mount -t sysfs sys ${ROOTDIR}/sys

chroot ${ROOTDIR} grub-install --target=x86_64-efi  --removable --efi-directory=/boot/efi
chroot ${ROOTDIR} update-grub

umount ${ROOTDIR}/sys
umount ${ROOTDIR}/proc
umount ${ROOTDIR}/dev

# Get a partition uuid of system
# In case of Apertis it is "/dev/vda6"
UUID=$(blkid /dev/vda6 -o value -s UUID)

cat > ${ROOTDIR}/boot/efi/EFI/BOOT/grub.cfg <<E_O_F
search.fs_uuid $UUID root hd0,gpt2
set prefix=(\$root)'/boot/grub'
configfile \$prefix/grub.cfg
E_O_F

```

**Comment by sangorrin** [comment]
Just for the record. Go debos uses a virtio disk such as /dev/vda and it is exposed (I believe) as $IMAGE. Once I realized that (I thought that $IMAGE meant the raw image file, not /dev/vda), this is how I solved the problem for grub-pc (legacy bios).

  - action: run
    chroot: true
    command: grub-install --target=i386-pc ${IMAGE}

  - action: run
    chroot: true
    command: update-grub

If you need UEFI, you can use @d4s script or this example: https://gitlab.collabora.com/snippets/4

Thanks,
Daniel
