### ISSUE TITLE
Allow to run without fakemachine

### ISSUE THREAD

**Issue by bhush9** [go-debos/debos#133]
https://github.com/go-debos/debos/blob/f8d7e4804f19e963682aa93d23737735ec7d7103/cmd/debos/debos.go#L134-L141

Currently, it checks if fakemachine is supported (which in turns checks if /dev/kvm exists on host) but doesn't check if fakemachine is actually works or not.

I can workaround by not having /dev/kvm file. But it would be good to have option to run it without fakemachine.

**Comment by smcv** [comment]
See also #185.

**Comment by sjoerdsimons** [comment]
just merged #185
