### ISSUE TITLE
actions: image-partition: add support for partman-crypto and grub

### ISSUE THREAD

**Issue by ant9000** [go-debos/debos#137]
Automating bootloader and rootfs encryption to images is already possibile, but relatively difficult.
I came up with working solutions to both problems, but I find them inelegant and unnecessarily complex:

  https://github.com/ant9000/debian-usb
  https://github.com/ant9000/debian-luks

I'm very keen to get advice on how to do it better.

How difficult would it be to integrate partman-crypto support into the image-partition action, and add a setup for grub?

Antonio

**Comment by obbardc** [comment]
how your recipe does this using a script currently is perfectly fine, and the generally accepted way to do this in debos. Hope that helps.
