### ISSUE TITLE
Template variables set via CLI option are mangled because of insufficient escaping

### ISSUE THREAD

**Issue by silbe** [go-debos/debos#141]
Template variables that are passed on the command line and contain special characters have incorrect values inside the template during actual execution (inside `fakemachine`). Even worse, the YAML template is expanded and parsed both with the original value (outside `fakemachine`) and with the shell-interpreted value (inside `fakemachine`). Depending on exactly how they're used inside the template, we may end up with invalid YAML during the first pass if we shell-escape the variables before passing them to `debos` because e.g. `\$` is not a valid escape sequence in YAML.

This happens because [`fakemachine.Machine.RunInMachineWithArgs()`](https://github.com/go-debos/fakemachine/blob/9316584144e259219bb20ca7b39774c01d601e36/machine.go#L608) does not shell-escape `args`; there's even a FIXME comment right there.

Either `fakemachine` or `debos` should shell-escape the arguments; `fakemachine` most likely is the proper place to do it but I don't know the code base well enough to be sure.

As a concrete example, try using a template variable with value `$5$xrmbIAjkTjp3$QAyDS7xfwmIxzN3G/90dugq59C.14Ke9YDXmGRa7572` (SHA-256 hashed password: `secret`).

**Comment by sjoerdsimons** [comment]
This should be fixed now in master ; mind that if you pass these template variables to a shell scripted you should also use the new `escape` template function e.g. `{{ escape $password }}` to fully escape the argument for the shell
