### ISSUE TITLE
Open a shell in the fakemachine on error

### ISSUE THREAD

**Issue by em-** [go-debos/debos#15]
When something breaks nothing beats opening a shell and poking things.

Ideally all the exec'ed programs should be (optionally) run as "$PROGRAM || sh". Of course that's a wild simplification as we want `$PROGRAM` output to be mangled by `debos` while the shell need access to the user's stdin/stdout, we need to print a nice header _before_ firing up the shell, the return value should be the original error, etc. etc., but hopefully you get the point. :)

Note that to be useful the shell should be fired in the same `fakemachine` as the command that failed, otherwise developers won't be able to properly inspect what went wrong.

**Comment by sjoerdsimons** [comment]
note that there is support for not running in fakemachine but with sudo as well.. 

But yes if we add support for "breaking" at the point of failure it should do that in the current environment.

**Comment by d4s** [comment]
Closed by #31
