### ISSUE TITLE
Cleanup the directory "/script" from target

### ISSUE THREAD

**Issue by d4s** [go-debos/debos#151]
Action run starting the script in chroot adds the "/script" to target image/tarball.
Need to cleanup that directory in case if it has been created by Debos.

**Comment by fdanis-oss** [comment]
I think there is 2 possible ways to solve this:
- move scripts from `/script` to `/tmp/script`,
- add a defered os.RemoveAll() call for all binded mount points created by systemd.nspawn.

Any advice?

**Comment by d4s** [comment]
I also thought about moving to `/tmp/script`
Since the defered removing can probably remove directory existing before which could cause unpredictable results. For sure wwe can save the state of such directory but moving to `/tmp` is more clear as for me.
Let me to check with Apertis build if moving to `/tmp/scripts` have no side effects.
