### ISSUE TITLE
Support for forcing fat32

### ISSUE THREAD

**Issue by weinholtendian** [go-debos/debos#169]
Hello! There are some Raspberry Pi Compute Module 3s that can't boot from fat16. I ran into a compute module like that and could successfully boot it after recreating the boot partition with `mkfs.vfat -F32 ...`.

Unfortunately there doesn't appear to be any way to specify fat32 by force; the setting "fs: fat32" is interpreted as "fs: vfat" and a fat16 file system is created (the partition is only ~63MB).

There's mention of this problem at the end of this page: https://www.raspberrypi.org/documentation/hardware/computemodule/cm-emmc-flashing.md

**Comment by andhe** [comment]
From mkfs.fat(8) manpage:
```
       -F FAT-SIZE
           Specifies the type of file allocation tables used  (12,  16  or  32
           bit).   If nothing is specified, mkfs.fat will automatically select
           between 12, 16 and 32 bit, whatever fits better for the  filesystem
           size.
```

I'm not sure I see a reason why not just always  force fat32. I think fat12 and fat16 are uncommon enough these days that everyone basically assumes fat = fat32 nowadays. Basing the default on the partition size will most likely be seen as an unhappy surprise by most people who haven't read every detail of every manpage.

Any objections against just adding a hardcoded "-F32" here?:
https://github.com/go-debos/debos/blob/master/actions/image_partition_action.go#L267
