### ISSUE TITLE
behavior of run action after filesytem-deploy

### ISSUE THREAD

**Issue by sangorrin** [go-debos/debos#175]
Hi,

I think that run actions that occur _after_ the filesystem-deploy action should not affect the contents of the image. In other words, once the filesystem is deployed to the loop device, changes to the chroot environment should not be deployed.

Current behavior does deploy those files. For example, the following sequence will produce an image with "/etc/packages.txt" despite I haven't deployed that file into the image.

```
  - action: filesystem-deploy
    description: Deploying filesystem onto image

  - action: run
    chroot: true
    command: dpkg --list > /etc/packages.txt
```

Is that a misunderstanding from my side?

Thanks
Daniel

**Comment by obbardc** [comment]
all that `action: filesystem-deploy` does is copy the files from a temporary dir to the image which has been partitioned. it can be called at any time.
After it has been called, any actions are switched to work directly on on the deployed image.

If that answers your question, please feel free to close the ticket.

**Comment by sangorrin** [comment]
@obbardc thanks for the explanation. It might be a good idea to mention that "switch" in the documentation. I believe that the behavior of the action "run" (with chroot enabled) changes significantly enough to mention it. For example, it is only after the "switch" that we are able to do stuff like `grub-install`.
