### ISSUE TITLE
Add the ability to share code between recipes

### ISSUE THREAD

**Issue by rperier** [go-debos/debos#183]
Hi,

First thanks for your work, debos is really a great tool with a lot of interesting idea.

The problem:
When you maintain a base of different recipes with common pattern between all these recipes (like packages or just actions), you have to duplicate a lot of code between all of these recipes. When you deal with powerful build systems like yocto, a common rule is to factorize code and properties between bb file (by including other bb for example) , simply because it avoids to duplicate data but it is also more simple to maintain later (I don't call about the object approach, with inheritance, because it's not in the scope of the discussion)

Proposal:
Either use a yaml syntax for including or importing another recipes (not sure it is possible), or use a dedicated action to execute a "sub recipe" : we could imagine a generic recipe that is executed in place before the rest of the "parent recipe". Or a special syntax that is specific to debos for this purpose

Regards,
Romain

**Comment by JBBgameich** [comment]
Is the recipe action already what you need? https://godoc.org/github.com/go-debos/debos/actions#hdr-Recipe_Action

**Comment by obbardc** [comment]
the recipe action should answer your question, could you close the ticket if so please?

**Comment by rperier** [comment]
Oh yeah, it does the trick sorry !
Thanks,
Romain
