### ISSUE TITLE
Add live-build-like match-based overlay folders

### ISSUE THREAD

**Issue by em-** [go-debos/debos#19]
Live-build has a fancy match-based overlay system, where it looks for the folders matching the current suite, arch and platform, even partially.

It basically expands the (suite,arch,platform) tuple and automatically overlays the contents of any existing folder that matches the expansion:

```
$ bash -c 'SUITE=buster; ARCH=amd64; PLATFORM=uefi; echo {suite,$SUITE}-{arch,$ARCH}-{platform,$PLATFORM}'
suite-arch-platform suite-arch-uefi suite-amd64-platform suite-amd64-uefi buster-arch-platform buster-arch-uefi buster-amd64-platform buster-amd64-uefi
```

Having some kind of folder matching for overlays in `debos` could be useful, doing that through templates becomes quite verbose very quickly.

**Comment by sjoerdsimons** [comment]
That's not a live-build feature; it's one of the image builder tools you're using... It's also sometime i've disliked from day one, so no, not something debos is intended to support.

**Comment by em-** [comment]
I see. Alternatively I think it would make sense to refactor the current suite-arch-platform overlays in several smaller and more meaningful overlays, so from the YAML it's more clear what going on. Anyhow, I'm closing this. Thanks for the feedback! :)

**Comment by sjoerdsimons** [comment]
Yes and note that some of those really didn't belong in the ospack in the first place, but were done there as linaro-image-tools didn't have the flexibility needed to do it at the image bild step
