### ISSUE TITLE
systemd-nspawn: unrecognized option '--resolv-conf=off'

### ISSUE THREAD

**Issue by rnjudge** [go-debos/debos#194]
I tried debos for the first time on an Ubuntu 18.04.3 LTS VM (systemd-237-3, golang-1.13, kernel-4.15.0-45-generic, debos @ commit 292995b52169f217cbcdf23e4e3dee470039d1d8)

I ran the following steps but got an error during the debootstrap build. 

```
$ go get -d github.com/go-debos/debos/cmd/debos
$ cd github.com/go-debos/debos/cmd/debos
$ go build
$ ./debos minideb.yaml
```

Error:
```
<snippet>
2020/01/03 11:18:44 Debootstrap | I: Unpacking ca-certificates...
2020/01/03 11:18:45 Debootstrap | I: Unpacking libssl1.1:amd64...
2020/01/03 11:18:47 Debootstrap | I: Unpacking openssl...
2020/01/03 11:18:47 Debootstrap | I: Configuring the base system...
2020/01/03 11:18:47 Debootstrap | I: Configuring apt-transport-https...
2020/01/03 11:18:48 Debootstrap | I: Configuring libssl1.1:amd64...
2020/01/03 11:18:48 Debootstrap | I: Configuring openssl...
2020/01/03 11:18:48 Debootstrap | I: Configuring ca-certificates...
2020/01/03 11:18:50 Debootstrap | I: Configuring libc-bin...
2020/01/03 11:18:51 Debootstrap | I: Configuring ca-certificates...
2020/01/03 11:18:51 Debootstrap | I: Base system installed successfully.
2020/01/03 11:18:52 apt clean | systemd-nspawn: unrecognized option '--resolv-conf=off'
2020/01/03 11:18:52 Action `debootstrap` failed at stage Run, error: exit status 1
```

To get rid of this issue and successfully build, I removed the error-ing option in `commands.go`:
```
diff --git a/commands.go b/commands.go
index 52704c5..4a1201b 100644
--- a/commands.go
+++ b/commands.go
@@ -223,7 +223,7 @@ func (cmd Command) Run(label string, cmdline ...string) error {
                options = append(options, cmdline...)
        case CHROOT_METHOD_NSPAWN:
                // We use own resolv.conf handling
-               options = append(options, "systemd-nspawn", "-q", "--resolv-conf=off", "-D", cmd.Chroot)
+               options = append(options, "systemd-nspawn", "-q", "-D", cmd.Chroot)
                for _, e := range cmd.extraEnv {
                        options = append(options, "--setenv", e)
 
```

For reference, here's the yaml file I was using to build with (uploaded as .txt to satisfy github attachment requirements)
[minideb.yaml.txt](https://github.com/go-debos/debos/files/4027284/minideb.yaml.txt)

Is this a unique failure or can I open a PR for this?
Thanks in advance.

**Comment by joshuagl** [comment]
It looks like systemd-nspawn gained the `resolv-conf` option some time between v237 (shipped in Ubuntu Bionic 18.04LTS - [ref](https://manpages.ubuntu.com/manpages/bionic/en/man1/systemd-nspawn.1.html)) and v240 (shipped in Ubuntu 19.04 - [ref](https://manpages.ubuntu.com/manpages/disco/en/man1/systemd-nspawn.1.html)).

If the option is not explicitly set to off then it defaults to auto, which behaves differently depending on what other options were supplied to systemd-nspawn.

**Comment by rnjudge** [comment]
Nice find, @joshuagl. I don't see a requirements file in the debos project but perhaps one should be added to document recommended system/package requirements.

**Comment by obbardc** [comment]
yep, agreed. let's add minimum systemd version (>=240) to requirements in readme and debian/control.

**Comment by flaurencin** [comment]
Debian bullseye fails for the same reason, . Hope it will be fixed quickly. @rnjudge thanks for the quick and dirty fix.
The weird thing is that it comes with

> Package: systemd
> Version: 245.6-1
> Installed-Size: 14406
> Maintainer: Debian systemd Maintainers <pkg-systemd-maintainers@lists.alioth.debian.org>
> Architecture: amd64

**Comment by obbardc** [comment]
hi @flaurencin 
Are you running the debos package from Debian or installed from source? if from source, can you tell me wheter it's master or another commit? if package, what version?

btw, I am running from source on debian sid which has the same version of systemd, no issues thus far.

**Comment by flaurencin** [comment]
Running from Linux Mint 19.3 Ubuntu derivated. 
I thougth the command was running inside a vm ?
I was running from source it was the last master 8 days ago. I switched to another tool but if needed I could retry.
It was relying on deboostrap 1.0.95Ubuntu0.6

Does it help ?

**Comment by obbardc** [comment]
Right so debian bullseye is running systemd 245.6-1 (https://packages.debian.org/bullseye/systemd)
and ubuntu bionic is running systemd 237-3 (https://packages.ubuntu.com/bionic/systemd)

**Comment by obbardc** [comment]
As per https://github.com/go-debos/debos/issues/411#issuecomment-1929754499 we are now requiring newer systemd.
