### ISSUE TITLE
apt/dpkg manages to corrupt the one single package

### ISSUE THREAD

**Issue by bhush9** [go-debos/debos#195]
I am not super sure what is wrong with this package, but maybe it has got to do with it have many files.

In either case, while I can reproduce it reliably with actual recipe I've failed to reproduce this with smaller testcase.

```
2020/01/09 12:40:45 apt | Selecting previously unselected package breeze-icon-theme.
2020/01/09 12:40:45 apt | Preparing to unpack .../191-breeze-icon-theme_4%3a5.65.0+p18.04+git20191223.0030-0_all.deb ...
2020/01/09 12:40:45 apt | Unpacking breeze-icon-theme (4:5.65.0+p18.04+git20191223.0030-0) ...
2020/01/09 12:40:47 apt | dpkg: error processing archive /tmp/apt-dpkg-install-rn8Tci/191-breeze-icon-theme_4%3a5.65.0+p18.04+git20191223.0030-0_all.deb (--unpack):
2020/01/09 12:40:47 apt |  corrupted filesystem tarfile - corrupted package archive
```

While apt is installing packages this appears, and in the end..

```
2020/01/09 12:42:20 apt | Unpacking qml-module-ofono:arm64 (0.90+16.10.20160901-0ubuntu1) ...
2020/01/09 12:42:20 apt | Errors were encountered while processing:
2020/01/09 12:42:20 apt |  /tmp/apt-dpkg-install-rn8Tci/191-breeze-icon-theme_4%3a5.65.0+p18.04+git20191223.0030-0_all.deb
2020/01/09 12:42:21 apt | E: Sub-process /usr/bin/dpkg returned an error code (1)
2020/01/09 12:42:21 Action `recipe` failed at stage Run, error: exit status 100
```

Since I can not produce smaller test case, here we go with the large/actual recipe: https://invent.kde.org/bshah/devices

`debos  -t device:pinephone -t variant:plamo base.yml` is command I am using

I have also tried adding extra memory by adding -m 10G as a argument if that was issue but it doesn't seem to make a difference. I really would love ideas on what is going on here.

**Comment by shadeslayer** [comment]
Have you tried eliminating the network as a potential source of failure by using apt-cacher-ng to cache the download between multiple runs?

**Comment by bhush9** [comment]
I have not, but I am 85% sure about this not being network issue tbh. GIven,

- When this happens, multiple machine and CI can reproduce this error
- Usually installing breeze-icon-themes earlier or in different package set before failing package set helps.

I need to figure out if or how I can plug apt-cacher-ng with the debos first though if I want to test this.

**Comment by obbardc** [comment]
hi @bhush9 
Do you have any update on this ?

**Comment by bhush9** [comment]
I will try to produce minimal test-case. I didn't manage to figure out how to get apt-cacher-ng working. But I am reasonably sure that I can have some kind of minimal test-case.

**Comment by obbardc** [comment]
If you could share a test-case that reproduces this that would be great (it doesn't have to be minimal).

**Comment by obbardc** [comment]
anything to report @bhush9 or can we consider this closed ?

**Comment by bhush9** [comment]
I'm honestly not sure how to help here 

https://build.plasma-mobile.org/view/All/job/img_plamo_pinephone/

This build failed like 4 times in row with the error reported above. When I tried reproducing this locally it did not fail.

And then from 2 days builds are passing correctly.

So 🤷

**Comment by obbardc** [comment]
Yeah that smells like a network issue to me, is it random packages it fails
on or is there a pattern?
Pipeline seems to fail quite often.

I'd probably try to get apt-cacher running next to download the packages
first.

**Comment by JBBgameich** [comment]
There is a pattern: It always fails on the breeze-icon-theme package.

**Comment by obbardc** [comment]
ah, i just saw that now I am back at the PC.
interestingly that's the only package downloaded from https://archive.neon.kde.org/unstable

**Comment by obbardc** [comment]
okay I had another look, it looks like all of the good builds do not install `breeze-icon-theme` whereas the bad builds install `breeze-icon-theme` ?

**Comment by bhush9** [comment]
`breeze-icon-theme` is installed by all builds, it's just where it fails... we download most package from the archive.neon.kde.org. Actually also if I remember it correctly this used to fail also with `adwaita-icon-theme` package earlier

Anyway, whenever I hit this problem my "get a thing working right now" solution is to install a package as much as early I can do and without grouping it together with other packages.

https://invent.kde.org/bshah/devices/-/commit/efae337f382b316355b33ead01939eb3929cdced see e.g.

As I've said earlier I very much doubt as this is network issue as at least 4-5 people independently on their machines, as well as two different jenkins instances, and various different recipes were able to reproduce this, and always on 2 packages. But at same time I've no idea what else this can be then apart from dpkg bugging out itself.. :frowning:

**Comment by bhush9** [comment]
And now all of sudden builds started failing : https://build.plasma-mobile.org/view/All/job/img_plamo_pinephone/117/ again .... I am not sure what is going on there though.

**Comment by obbardc** [comment]
be good if you can pull the downloaded package from the fakemachine after
it fails to see if it actually is corrupt or not.

Another option (for debug) is to download the package and call "dpkg" and
"apt-get install -f" separately.

**Comment by obbardc** [comment]
Please reopen the issue with more information if this is still relevant.
