### ISSUE TITLE
mature  or abandoned

### ISSUE THREAD

**Issue by stappersg** [go-debos/debos#196]
Currently it is hard to tell if  **go-debos/debos** is an abandoned project or a mature project.

Please show the world that this project is alive and kicking.

I volunteer to help

**Comment by stappersg** [comment]
Merging #188 would be a good thing.

**Comment by stappersg** [comment]
Issue #134, _building image inside docker container fails when trying to open system bus_, got ignored for thirteen months.

Please prevent that #134 keeps radiating _this project is abandoned_ by either stating something like _nested in docker is no project goal_  or by simply closing the wishlist issue.

**Comment by d4s** [comment]
The project itself is alive and heavily used ;)
Hovewer we're busy with other tasks sometime, so answer/reaction could be not so fast as desired.
Regarding #134 -- probably it should be closed since we provide Debos built in docker: https://hub.docker.com/r/godebos/debos/builds

**Comment by sjoerdsimons** [comment]
As @d4s says and like i mentioned as fosdem to you; We're heavily using debos for projects (and so are others). Just like a lot of open-source project time is limited :).  

Helping gardening the issues would be much appreciated ofcourse.
