### ISSUE TITLE
Use artifactdir to place images for consistency

### ISSUE THREAD

**Issue by sangorrin** [go-debos/debos#214]
Hi :)

I noticed that the image partition does not use the artifactdir folder to place the final image.
https://github.com/go-debos/debos/blob/master/actions/image_partition_action.go

[Note] Although for some reason I couldn't understand PostMachineCleanup uses it
https://github.com/go-debos/debos/blob/master/actions/image_partition_action.go#L524

In contrast, the pack action does indeed use artifactdir to place the result rootfs
https://github.com/go-debos/debos/blob/master/actions/pack_action.go#L35

Wouldn't it be more consistent to use the artifactdir on both?
Thanks

**Comment by obbardc** [comment]
actually, image-partition action does place the created image under ArtifactDir while the action is running, it's just not clear since that's handled under fakemachine :-)

**Comment by sangorrin** [comment]
Hi @obbardc, thanks for your reply.

What I meant is that the image-partition action does not output the image to artifactdir.
I prepare a simple example here where you can see the behavior I am referring too:

https://github.com/sangorrin/debos-artifacts-behavior

Thank,
Daniel
