### ISSUE TITLE
actions: debootstrap: debootstrap gives a warning about no such file or directory /etc/apt/apt.conf.d

### ISSUE THREAD

**Issue by obbardc** [go-debos/debos#219]
The debootstrap action shows a misleading warning:

```
2020/06/15 07:24:05 Debootstrap | W: Unable to read /etc/apt/apt.conf.d/ - DirectoryExists (2: No such file or directory)
```

**Comment by andhe** [comment]
FWIW I just verified a hack like this silences the warning by debootstrap action:

```diff --git a/actions/debootstrap_action.go b/actions/debootstrap_action.go
index 506270c..fb976db 100644
--- a/actions/debootstrap_action.go
+++ b/actions/debootstrap_action.go
@@ -159,6 +159,11 @@ func (d *DebootstrapAction) RunSecondStage(context debos.DebosContext) error {
 
 func (d *DebootstrapAction) Run(context *debos.DebosContext) error {
        d.LogStart()
+
+       /* HACK: apt warns if directory is missing, so create it. */
+       mkaptdircmd := []string{"mkdir", "-p", "/etc/apt/apt.conf.d"}
+       debos.Command{}.Run("Debootstrap (prep)", mkaptdircmd...);
+
        cmdline := []string{"debootstrap"}
 
        if d.MergedUsr {
```

I guess the main question is if maybe fakemachine should provide a sane apt configuration out of the box or if debos should work around it like this?

**Comment by obbardc** [comment]
yeah, a hack like that was exactly what i was thinking.

perhaps it should remove the directory after running if its empty.

**Comment by andhe** [comment]
Since this is inside fakemachine, I don't really see much need for cleaning up. However, the hack should possibly also be added to the apt action which I guess also generate this warning (but haven't looked), for those with recipes that doesn't first use the debootstrap action.
