### ISSUE TITLE
Segfault at the end of debootstrap action @ debos-recipes/rpi64

### ISSUE THREAD

**Issue by mzew** [go-debos/debos#245]
Hello,
I'm always getting the following error while building debos-recipes/rpi64. Tested on archlinux running in go-debos/debos docker container and freshly installed Debian 10.7.0. Host is amd64 in both cases

```
2021/01/22 17:28:27 debootstrap.log | 2021-01-22 17:28:21 URL:http://deb.debian.org/debian/pool/main/x/xz-utils/liblzma5_5.2.5-1.0_arm64.deb [164436/164436] -> "/scratch/root//var/cache/apt/archives/partial/liblzma5_5.2.5-1.0_arm64.deb" [1]
2021/01/22 17:28:27 debootstrap.log | 2021-01-22 17:28:21 URL:http://deb.debian.org/debian/pool/main/z/zlib/zlib1g_1.2.11.dfsg-2_arm64.deb [87944/87944] -> "/scratch/root//var/cache/apt/archives/partial/zlib1g_1%3a1.2.11.dfsg-2_arm64.deb" [1]
2021/01/22 17:28:27 debootstrap.log | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
2021/01/22 17:28:27 debootstrap.log | Segmentation fault
2021/01/22 17:28:27 Action `debootstrap` failed at stage Run, error: exit status 1
Powering off.
```

**Comment by obbardc** [comment]
reproduced

**Comment by damianfurrer** [comment]
I ran into the same issue, when trying to build mobian.
The docker image niluxbe/debos worked for me.
`docker pull niluxbe/debos`
+ replace godebos/debos with niluxbe/debos in your build script.

**Comment by obbardc** [comment]
Can you try the latest `dodebos/debos` docker image? It's now based on debian bullseye.

**Comment by obbardc** [comment]
also seems like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=988174 is related

**Comment by obbardc** [comment]
@mzew @damianfurrer please re-open if still an issue with latest docker images
