### ISSUE TITLE
actions: debootstrap: different result from naked deboostrap and debos debootstrap

### ISSUE THREAD

**Issue by dbaudio-sfe** [go-debos/debos#250]
Hi, 

we are using debos (with great success so far) for our embedded armhf system. 

No I came across an issue I can not explain. 

When running a naked debootstrap I get a certain chroot. 
Doing the same within a debos recipe gives me a smaller system. About 40 packages are missing. 

**debos build (run with -v):**

sudo /opt/src/gocode/bin/debos -v --artifactdir=../../ get-packages-from-extern-CrossArch.yaml

2021/03/10 14:02:13   - Action: debootstrap, Description: 
2021/03/10 14:02:13     Suite: buster
2021/03/10 14:02:13     Mirror: http://deb.debian.org/debian
2021/03/10 14:02:13     Variant: 
2021/03/10 14:02:13     KeyringPackage: 
2021/03/10 14:02:13     KeyringFile: 
2021/03/10 14:02:13     Components: [main]
2021/03/10 14:02:13     MergedUsr: true
2021/03/10 14:02:13     CheckGpg: true
2021/03/10 14:02:13 fakemachine not supported, running on the host!
2021/03/10 14:02:13 ==== debootstrap ====
2021/03/10 14:02:13 Debootstrap | I: Retrieving InRelease 
...

**debootstrap:**

sudo debootstrap --components=main --merged-usr --arch=armhf --foreign buster test/ http://deb.debian.org/debian /usr/share/debootstrap/scripts/unstable

It feels a bit like the debos version builds a minbase, but there is no variant given. 
And I don't know how to get more debugging information. 

Could you give any good advice here?

Btw, is there an IRC for debos? Or is this the best way to address issues?

Best regards, 

Sebastian

**Comment by obbardc** [comment]
interesting, can you post a list of which packages are installed (hence the missing packages) into both chroots?

a ticket here is fine for discussions :-)

**Comment by dbaudio-sfe** [comment]
ok, another layer 8 issue. 
I worked with the assumtption, that a buildd variant would take the base and add to it. 
But looking at the debootstrap scripts it clearly does not:

if doing_variant - || doing_variant fakechroot; then
                #required="$required $(get_debs Priority: important)"
                #  ^^ should be getting debconf here somehow maybe
                base="$(get_debs Priority: important)"
        elif doing_variant buildd; then
                base="apt build-essential"
        elif doing_variant minbase; then
                base="apt"
        fi


And my problematic builds used that buildd variant that I removed for later test it did not notice the difference. 
And that in combination with an offline mirror of the debian repositories was too much for me. 

So sorry for wasting your time. But you helped me wrap my head around things. So thank you very much. 

And thanks to the whole debos team for this awesome piece of software!

**Comment by obbardc** [comment]
no problem; i will close this now but feel free to open another ticket in case of more questions/bugs/etc :)
