### ISSUE TITLE
Why Debian instead of Ubuntu Server?

### ISSUE THREAD

**Issue by jerkstorecaller** [go-debos/debos#252]
Seems like a very nice tool, and I look forward to using it.

I was wondering why this tool targets Debian, instead of the more popular (and optionally commercially-supported) Ubuntu Server? I'm guessing the developers' employer uses Debian internally and this drove the decision, but what is their reasoning in choosing Debian over Ubuntu Server? I'm curious and it could help me appreciate Debian more.

**Comment by obbardc** [comment]
a lot of our projects are based on Debian :-). see for example [Apertis](https://apertis.org/)

you can of course build Ubuntu images using debos, since Ubuntu is a Debian derivative.

**Comment by jerkstorecaller** [comment]
Glad to hear it works with Ubuntu, I thought you relied on stuff specific to Debian's installer. That said, I'm worried about going off the beaten path.

What I was wondering is what pushed you to Debian over Ubuntu Server? This is not some "what's your favorite distro" pointless question, you seem well-placed to provide an answer that's relevant in the thing I'm doing (building an embedded system).

From what I've experienced and read Debian and Ubuntu Server are pretty much the same, except that:

1. Ubuntu Server LTS has 5 year support window, while Debian has only 3
1. I can get official Ubuntu support from Canonical, if I'm ever desperate
1. I've seen quite a few 3rd parties use Ubuntu PPAs to provide the latest version of a standalone package, for example getting the latest version of git even on Ubuntu 18.04. Debian has backports, but that's not the same, it only gives you a single bump to the version from unstable. So if you want "stable, old system but with specific packages updated to latest" this seems easier on Ubuntu. (Of course you can always compile packages yourself from source).
1. Anecdotal, but based on the projects I've been exposed to, Ubuntu is the most tested distro by developers, while other distros can be an afterthought. It's like the Windows of Linux.

If I could hear arguments in favor of Debian relevant to the sort of projects debos is used on, it would help me make an informed decision. According to my research the advantages for Debian are:
1. Due to community-oriented structure, there's almost zero chance of a stunt like Red Hat did with CentOS 8 (ceasing support 8 years early), while a company like Canonical could in theory decide to drop 20.04 anytime they want
2. Ubuntu's increased promotion of snaps, which auto-update and don't let you disable updates (unless you disable snapd altogether), could add complexity in the future. For example if important server packages like Postgres are moved to snap.

I realize this could be considered off-topic, but I think it might be relevant to others too. I'm only asking about your own decisions, I didn't give any info about my situation that would make your advice specific to me.

**Comment by sjoerdsimons** [comment]
This is off-topic; Closing this one.

We're not pushing anything here; It's a tool primary targetted at building images for Debian based distributions, of which Ubuntu is one of many.  And tbh for what it's being used (primarily appliance and embedded systems) Ubuntu Server really is not relevant at all ;).
