### ISSUE TITLE
Installing a debos ostree rootfs with an interactive installer

### ISSUE THREAD

**Issue by jpace121** [go-debos/debos#355]
Hi!

debos is a great tool. I'm very interested in building custom debian based ostree images, since I firmly believe that is the way of the future for IOT device management, debian based distros are the distros of choice in my industry, and debos is by far the best tool on the market for building debian based ostree images.

Is there any integration with an interactive installer so we can build an image with debos and then install it on a device that needs to be custom partitioned? Specifically, the hardware I want to deploy to will have a multi terabyte hard drive, and I don't really want to build a multi-terabyte image in debos...

Thanks!

**Comment by obbardc** [comment]
unfortunately I think this would require some external tooling, potentially using d-i with a preseed file etc

Typically I gzip large pre-partitioned images then flash them to drive using bmap, saves time :-)
