### ISSUE TITLE
fakemachine options

### ISSUE THREAD

**Issue by ttwsyf-dev** [go-debos/debos#357]
Hi this is just a question really

I remember reading that there's a way to pass options to fakemachine from debos but I can't seem to find it now.

Can someone please remind me how it's done?

Thanks very much in advance

Best regards
Mike

**Comment by obbardc** [comment]
hi!
Here's the docker command I use with debos on Debian:
```
docker run \
  --rm \
  -w /recipes \
  -v $(pwd):/recipes \
  -u $(id -u):$(id -g) \
  --security-opt label=disable \
  --group-add=$(getent group kvm | cut -d : -f 3) \
  --device /dev/kvm \
  --cap-add=SYS_PTRACE \
  --tmpfs /scratch:exec \
  -e TMP=/scratch \
  godebos/debos:latest \
  rpi64/debimage-rpi64.yaml --debug-shell
```
It could be better placed inside the readme somehow...

**Comment by obbardc** [comment]
> so I followed your snippet to the letter and ended up right back at exactly the same error I got in my second post.
Do you have an example recipe which reproduces this ? I assume basic recipes which don't do ostree stuff work fine?

> _How do **you** get it to cooperate?_

The docker command I posted above works for me, I am running a Debian Unstable host :-).


> You also didn't answer my other questions. I had to install QEMU on my workstation which I really didn't want to do since although Debian Wiki tells you to only install 4 or 5 packages it transitively pulls in dozens.
> So I return to a question I've already asked:
> _Is it in fact the case that the KVM backend actually **requires** QEMU?_
> That may be the standard way most people do it but it is not necessary. There are plenty of projects that make do with bare KVM. One such is weaveworks ignite which is boostrapped on top of AWS firecracker-microvm.
> The reason I'd really like to know is because my experience of QEMU on Debian was nothing short of disastrous (dependency hell big-time). I'd really like to get all that stuff off my machine and the usual accompanying libvirt stuff.

Right, for the kvm backend, all you need is `/dev/kvm` available on your host. We ship qemu and kvm inside the docker container, so there's no need to install qemu on your host.


> Finally, I return to another question I've already asked because I think it would make a lot of sense:
> 
> _Is is possible to run whatever fakemachine backend you chose/is chosen for you in a contaner?_
> 
> I assumed that when the kvm backend started getting used that that would take care of the issue in my second post. It didn't at all for the reasons you say in the docs I'm sure.

Right, by default debos chooses the "best supported" backend but to override that with the docker container you can do e.g.
```
docker run \
  --rm \
  -w /recipes \
  -v $(pwd):/recipes \
  -u $(id -u):$(id -g) \
  --security-opt label=disable \
  --group-add=$(getent group kvm | cut -d : -f 3) \
  --device /dev/kvm \
  --cap-add=SYS_PTRACE \
  --tmpfs /scratch:exec \
  -e TMP=/scratch \
  godebos/debos:latest \
  rpi64/debimage-rpi64.yaml --fakemachine-backend=kvm
```

You can try to pass `--help` instead of the recipe to see the full command usage, e.g:
```
Application Options:
  -b, --fakemachine-backend=[auto|kvm|uml|qemu] Fakemachine backend to use (default: auto)
```

> Except for Windows containers which don't interop with anything, containers are Linux. And I know _for sure_ you _can_ run bare KVM in a container.
> 
> I sincerely hope you don't interpret any of this as criticism. It isn't. I'm just very interested in the project and if you foresaw no inordinately challenging difficulties in running the backends in containers I might have a bash at it myself. I'd contribute back of course if I came up with something respectable enough to be seen in public. (FWIW, QEMU is surprisingly easy to build in a container.)
> 
> Thanks very very much for your help. I'd be fandabbydozey grateful if you could answer my three questions. My primary interest in the project is the ostree functionality and all the supporting actions you've built into debos like your handling of debootstrap which is superb.

I think the problem really is difference in permissions between inside the container and outside the container rather than anything inherently broken ;-)

> 
> I have a _very_ strong aversion to re-inventing the wheel.
> 
> No "not invented here" syndrome with me like!
> 
> Thanks again and I hope in advance
> 
> Best regards Mike
