### ISSUE TITLE
can I build for arm on x64?

### ISSUE THREAD

**Issue by tural-sadik** [go-debos/debos#389]
My host is x64 and I am trying to build for arm64. Whenever I start debos and check the processes I see qemu-system-x86 running when I was expecting to see qemu-system-arr

Does that mean in order to build for ARM I need to be building on arm?

**Comment by obbardc** [comment]
if you set `architecture: arm64` in the recipe, debos sets everything up to generate an arm64 image for you :-). It uses qemu-user-static to translate the binaries to x86.

So no, you don't need to be on arm to generate arm images.

**Comment by tsadigovAgmail** [comment]
Thanks for response. I came across the tool when trying to build radxa 

I don't know what a working debos look like so this may be a false negative. But I could not make it work with simple recipe. I was expecting the guest machine recognizing itself as arm architecture, but it seems like guest is running as x86

the command I am using is :
tural@debian:~/Desktop/debossample$ sudo debos --show-boot --verbose  small-recipe.yaml 

And the system freezes 

`2022/12/14 23:31:07 Recipe '/home/tural/Desktop/debossample/small-recipe.yaml':
2022/12/14 23:31:07   Architecture: armhf
2022/12/14 23:31:07   Actions:
2022/12/14 23:31:07   - Action: debootstrap, Description: 
2022/12/14 23:31:07     Suite: stretch
2022/12/14 23:31:07     Mirror: https://deb.debian.org/debian
2022/12/14 23:31:07     Variant: minbase
2022/12/14 23:31:07     KeyringPackage: 
2022/12/14 23:31:07     KeyringFile: 
2022/12/14 23:31:07     Certificate: 
2022/12/14 23:31:07     PrivateKey: 
2022/12/14 23:31:07     Components: [main]
2022/12/14 23:31:07     MergedUsr: true
2022/12/14 23:31:07     CheckGpg: true
2022/12/14 23:31:07   - Action: pack, Description: 
2022/12/14 23:31:07     Compression: gz
2022/12/14 23:31:07     File: rootfs.tar.gz
[    0.000000] Linux version 5.10.0-19-amd64 (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.149-2 (2022-10-21)
[    0.000000] Command line: console=ttyS0 panic=-1 systemd.unit=fakemachine.service
[    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
[    0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
[    0.000000] x86/fpu: xstate_offset[2]:  576, xstate_sizes[2]:  256
[    0.000000] x86/fpu: Enabled xstate features 0x7, context size is 832 bytes, using 'compacted' format.
[    0.000000] BIOS-provided physical RAM map:
[    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
[    0.000000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] reserved
[    0.000000] BIOS-e820: [mem 0x0000000000100000-0x000000007ffdffff] usable
[    0.000000] BIOS-e820: [mem 0x000000007ffe0000-0x000000007fffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000feffc000-0x00000000feffffff] reserved
[    0.000000] BIOS-e820: [mem 0x00000000fffc0000-0x00000000ffffffff] reserved
[    0.000000] NX (Execute Disable) protection: active
[    0.000000] SMBIOS 2.8 present.
[    0.000000] DMI: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.14.0-2 04/01/2014
[    0.000000] Hypervisor detected: KVM
`

**Comment by tsadigovAgmail** [comment]
I guess it worked with `-b uml` option, I need to check resulting image also

**Comment by tural-sadik** [comment]
I am not sure what was the issue with the other backend, but this option made it. It is working.
