### ISSUE TITLE
Missing developer documentation

### ISSUE THREAD

**Issue by martin-petzold** [go-debos/debos#392]
I would like to contribute a feature: https://github.com/tavla/debos/tree/feature/apt-properties

However, I am not so familiar with go and cannot install from my fork because transitive dependencies are pulled from "github.com/go-debos/debos" instead of my fork "github.com/tavla/debos". I already changed the "go.mod" and am using: `go install -a -v github.com/tavla/debos/cmd/debos@main`.

Could someone help me and/or maybe it would also make sense to create a developer documentation.

**Comment by obbardc** [comment]
hi @martin-petzold 

For development, I simply do something like:
```
go build -o debos cmd/debos/debos.go
```

**Comment by martin-petzold** [comment]
How can I avoid the access to the module cache via sudo (which seems to be root for some reason)?

**Comment by martin-petzold** [comment]
Answer: Use a path which is writable by the user: `export GOPATH=/opt/go/src`
