### ISSUE TITLE
how to find the size of ${ROOTDIR} ?

### ISSUE THREAD

**Issue by kprasadvnsi** [go-debos/debos#419]
I am trying to find the total size of ${ROOTDIR} and use this ( ${ROOTDIR} size + 600MB)  in the image-partition action to set the imagesize value.

**Comment by obbardc** [comment]
@kprasadvnsi Do you have an example recipe?

**Comment by kprasadvnsi** [comment]
```
#!/bin/sh

SIZE=$(du -s --block-size=MB ${ROOTDIR} | awk '{print $1}' | sed -e 's/MB//g')

echo $SIZE
```

I can run this script that give me the total size of ${ROOTDIR}  but now I don't how to take this value and use it in image-partition action

**Comment by kprasadvnsi** [comment]
```
{{- $architecture := or .architecture "arm64" -}}
{{- $platform := or .platform "archlinux" -}}
{{- $device := or .device "opi5plus" -}}
{{- $edition := or .edition "minimal" -}}
{{- $rootfs := or .rootfs (printf "rootfs-%s-%s-%s.tar.gz" $platform $edition $architecture) -}}

architecture: {{ $architecture }}

actions:
  - action: unpack
    file: cache/rootfs/{{ $rootfs }}

  - action: run
    chroot: false
    script: image.sh
```

This is how it looks right now .

**Comment by obbardc** [comment]
Sorry, it's not clear what you are trying to do. Are you trying to dynamically create an image based on the size of a rootfs?

**Comment by kprasadvnsi** [comment]
> Sorry, it's not clear what you are trying to do. Are you trying to dynamically create an image based on the size of a rootfs?

yes

**Comment by kprasadvnsi** [comment]
I am making an archlinux image for Orange Pi 5 board with different desktop environment. For each rootfs(different DE) the rootfs size will be different. If I set the **imagesize** manually then I can only set it to the highest value that can fit all these different variations of rootfs. 

setting the **imagesize** manually is a problem due to the fact I have guess the rootfs size each time I install/remove packages.

**Comment by kprasadvnsi** [comment]
It may not be relevant to this discussion but i thought I should include the way I am doing this in my current build system which is a bunch of shell scripts. 

```
info "Creating partitions..."

    SIZE=$(du -s --block-size=MB $CHROOTDIR | awk '{print $1}' | sed -e 's/MB//g')
    EXTRA_SIZE=600
    REAL_SIZE=`echo "$(($SIZE+$EXTRA_SIZE))"`
    
    #making blank .img to be used
    dd if=/dev/zero of=$IMGDIR/$IMGNAME.img bs=1M count=$REAL_SIZE 1> /dev/null 2>&1

    #probing loop into the kernel
    modprobe loop 1> /dev/null 2>&1

    #set up loop device
    LDEV=`losetup -f`
    DEV=`echo $LDEV | cut -d "/" -f 3`

    #mount image to loop device
    losetup -P $LDEV $IMGDIR/$IMGNAME.img 1> /dev/null 2>&1
```

**Comment by obbardc** [comment]
Why not just set the image size to something which caters for everything ? e.g. the size of the eMMC/block device ?

**Comment by kprasadvnsi** [comment]
These OS images will be for Micro SD card. Lets say I set the imagesize to 8GB. now the CLI OS image will take longer to write to a microsd card.

**Comment by obbardc** [comment]
For that we suggest to write using bmaptool, so only the used data is written to the card.

**Comment by kprasadvnsi** [comment]
I solved my issue by packing the rootfs then figure out the packed rootfs uncompressed size then call the image recipe with imagesize argument. This is not an elegant solution but it does wok in my case.
