### ISSUE TITLE
Blockers for using upstream debos

### ISSUE THREAD

**Issue by evelikov** [go-debos/debos#456]
Here's a list of blockers for us to use upstream debos instead of our fork:

- proper exitcode handling - any of https://github.com/go-debos/debos/pull/198 https://github.com/go-debos/debos/pull/278 or https://github.com/go-debos/debos/pull/303 - please add tests
- add option to install extra packages in the pacstrap stage - currently we implicitly install only "base" - https://github.com/go-debos/debos/issues/481
- relative partition sizes - https://github.com/go-debos/debos/pull/285

We've had a fork for 4 years, hope we get the above sorted before we hit 5 :crossed_fingers:

**Comment by obbardc** [comment]
`add option to install extra packages in the pacstrap stage - currently we implicitly install only "base"` is the only thing which hasn't got a pull request outstanding, perhaps you could open one ? I assume it should be very quick to get in.

**Comment by obbardc** [comment]
In the meantime, I have created https://github.com/go-debos/debos/issues/481 for the missing part.

**Comment by obbardc** [comment]
This isn't a constructive issue - it's just a list of other issues. Closing.
