### ISSUE TITLE
The MBR extended implementation causes a problem with a non-MBR configuration

### ISSUE THREAD

**Issue by robertkirkman** [go-debos/debos#473]
Hi I don't know enough about the project yet to know how to create a minimal reproducible example, but when i use [this](https://github.com/foxlet/VaporOS/blob/master/vapor-steamdeck-main.yaml) file with `debos`, if I use commit 03ec3cbfab6a73087ebbb58317f65e117342c1ba of `debos`  it works but if I use commit da773ccbc899d2f5b236f80db303062693f6f2b6 or any of the recent commits after that, the `debos` command gets stuck inside the fakemachine because of a partition named "extended" getting incorrectly created in the wrong place even though the `.yaml` file specifies `gpt` and not `mbr`

If I have time I will try to create a minimal reproducible example

**Comment by robertkirkman** [comment]
Thank you I tested that patch and the same `.yaml` file I tested with the other 2 versions of `debos` works with your msdos-fixes branch!

**Comment by sjoerdsimons** [comment]
Thanks for testing!
