### ISSUE TITLE
Overlap with vmdb2

### ISSUE THREAD

**Issue by stapelberg** [go-debos/debos#58]
debos looks very similar to https://github.com/larswirzenius/vmdb2/ :)

Perhaps you could collaborate or merge the two projects.

cc @larswirzenius @d4s

**Comment by larswirzenius** [comment]
I'm not interested in merging my Python project with a Go project, sorry.

**Comment by sjoerdsimons** [comment]
Neither am i interesting in merging with vmdb2 :) 

I did look at (very early) versions of vmdb2 and a bunch of other tools to come to the conclusion they weren't going the direction i was after when i started with what became debos. The current user side of things looks roughly similar (Which is a good thing as it mean we both had roughly the same conclusions of the problems of e.g. vmdebootstrap)

In any case having multiple projects with overlapping functionaltiy has never been an issue in open-source; especially not when things are in early stages so I don't have a problem at all both projects going their own direction and potentially from time to time learn from eachother

**Comment by liori** [comment]
Out of curiosity, how about [bootstrap-vz](https://github.com/andsens/bootstrap-vz) then? Are there any goals for debos that aren't satisfied by bootstrap-vz?
