### ISSUE TITLE
Running debos in a chroot

### ISSUE THREAD

**Issue by stappersg** [go-debos/debos#65]
Hi,

Debos is now in Debian and I have it installed in a chroot.

Testdriving `debos` with the rpi3 recipe reveals that some test on the host system are performed.
I don't understand why `/lib/modules` and Kernel are needed in early execution stage.

Screen shot:
```
root@yanur:/src/githubclones/debos-recipes/debian/arm64/image-rpi3# debos debimage-rpi3.yaml 
open /lib/modules: no such file or directory
root@yanur:/src/githubclones/debos-recipes/debian/arm64/image-rpi3# mkdir /lib/modules
root@yanur:/src/githubclones/debos-recipes/debian/arm64/image-rpi3# debos debimage-rpi3.yaml 
No kernel found
root@yanur:/src/githubclones/debos-recipes/debian/arm64/image-rpi3# 
```

Why the search for a kernel?

**Comment by d4s** [comment]
Hi, Debos uses Qemu (via fakemachine library) on top of current FS for build isolation and  root privileges 'emulation', so the kernel and modules are needed to start the qemu. Initrd is generated on-the-fly from current modules.

**Comment by stappersg** [comment]
On Wed, Feb 28, 2018 at 03:55:18AM -0800, Denis Pynkin wrote:
> Debos uses Qemu (via fakemachine library) on top of current FS for
> build isolation and  root privileges 'emulation', so the kernel and
> modules are needed to start the qemu. Initrd is generated on-the-fly
> from current modules.

With a bind mount of /lib/modules to chroot
kernel modules are indeed found.

Thanks for explaining why
