### ISSUE TITLE
should have a way to turn off metadata_csum for mkfs.ext*

### ISSUE THREAD

**Issue by smcv** [go-debos/debos#78]
When using a recent host distro (Debian >= stretch) to build images based on an older distro (Debian <= jessie), `mkfs.ext4` will enable the `metadata_csum` feature by default, but jessie's `e2fsck` doesn't understand that feature. I'm not sure whether jessie kernels understand it either (I'm currently working with a jessie derivative that happens to have a newer kernel).

vmdebootstrap automatically disables `metadata_csum` for jessie, but that's probably too much magic for debos' design. It would be useful to have a way to turn off that flag, even if it's just adding `^metadata_csum` or `-O ^metadata_csum` to the YAML somewhere.

**Comment by smcv** [comment]
Alternatively, perhaps the filesystems could be created by making a device node available in the chroot and letting the distro that's being bootstrapped format it? That would make sure it's created with options that the bootstrapped distro understands.

**Comment by andhe** [comment]
This issue talks about a specific problem which seems to be part of a larger general issue.

The problem has again become relevant in upcoming Debian release bookworm, which again brings new e2fsprogs features (AIUI this time it's `metadata_csum_seed`), which makes the created filesystem in the image incompatible with older releases (<= bullseye).

See  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031640#174

**Comment by sjoerdsimons** [comment]
fwiw you can already do `features:  ["^metadata_csum_seed"] ` in the partitions section to turn of specific features of e2fsprogs. Which i think means this issue can be closed now. This was added in  a1ee91aff3a6 so a while back already ;)

And yeah for debos we try not to encode any distribution specific knowledge in it like vmdebootstrap has.  The safest/most conservative  bet will always be building in a debos environment that matches the distribution you're building (e.g. use the debos bullseye docker container to build bullseye images).. Though i must admit i ofcourse also build images for e.g. stable debian on my bookworm/sid workstation, it just gets slightly in assuming you know what you're doing territory :)
