### ISSUE TITLE
Create a standard docker image with debos to push to docker hub

### ISSUE THREAD

**Issue by d4s** [go-debos/debos#9]

**Comment by macpijan** [comment]
Hello. I was struggling to run the debos on Ubuntu and I ended up trying to develop a Debian docker container for it. You can find my work here: https://github.com/3mdeb/debos/blob/add-dockerfile/docker/Dockerfile

Unfortunately, build for arch other than the native (`amd64`) fails at:
`Debootstrap (stage 2) | chroot: failed to run command '/debootstrap/debootstrap': Exec format error`

I also wrote a short post to document my triage: https://3mdeb.com/os-dev/our-first-look-at-debos-new-debian-images-generator/

If you have a clue why does it fail, I will be glad to fix and contribute the Dockerfile. `debos` seems like a nice project, but limiting the usage to Debian-only host seems a little bit limiting. Having a portable container could allow me (and possibly others) to take advantage of this tool more. Thanks.
