### ISSUE TITLE
RFE: pass http_proxy through to commands

### ISSUE THREAD

**Issue by smcv** [go-debos/debos#90]
For those of us not adjacent to a mirror, apt-cacher-ng in proxy mode is a useful way to speed up the test/debug/fix cycle. Setting `http_proxy` is probably the best way: that has the benefit that it can work for both debootstrap and apt, and the generated filesystem is left with a canonical mirror like `deb.debian.org` hard-coded into it (as opposed to having the proxy or a local mirror end up in `/etc` in the output).

I think this should be a command-line option or environment variable instead of part of the recipe, because it's really a fact about the machine/LAN where you're running debos rather than a fact about the recipe itself, and doesn't make a whole lot of sense to version-control.

`no_proxy` might also be useful to pass through, for the case where locally-served packages can't or shouldn't go through the proxy.

`https_proxy` and `ftp_proxy` are perhaps less useful but work the same way as http_proxy, so wouldn't need be significantly more code.

**Comment by zumbi** [comment]
Indeed, I second a package caching feature for debos.

**Comment by smcv** [comment]
#109 appears to fix this.
